name: PING_SERVER 

on:
  schedule: ## Schedule the job to run at a particular time.
    # * is a special character in YAML so you have to quote this string
    - cron:  '15 * * * *'

jobs: PING_SERVER
  deploy: 
    runs-on: ubuntu-latest  
    steps: 
    - uses: actions/checkout@master 
    - uses: actions/setup-node@master  
      with: 
        node-version: '14.x' 
    - run: npm install 
     - run: npm run ping